import { Queue, Worker } from 'bullmq';
import IORedis from 'ioredis';
import * as dotenv from 'dotenv';
import path from 'path';
import fs from 'fs/promises';

// AI Utilities
import { generateScripts } from './openai';
import { generateAudio } from './elevenlabs';
import { mixAudioFiles } from './audio_mixer';
import { uploadAudio } from './storage';
import { saveAudioRecord, publishEvent } from './db';

dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

const connection = new IORedis(process.env.REDIS_URL || 'redis://localhost:6379', {
    maxRetriesPerRequest: null
});

// Queue instances
export const ingestQueue = new Queue('ingest', { connection });
export const ttsQueue = new Queue('tts', { connection });
export const storeQueue = new Queue('store', { connection });


// --- WORKER 1: Ingestion & Script Gen ---

const ingestWorker = new Worker('ingest', async job => {
    console.log(`[Ingest Worker] Processing job ${job.id}: ${job.data.eventName}`);
    const { eventId, eventName, summaryText, eraLabel } = job.data;
    
    // 1. Call OpenAI for 4 scripts
    const scripts = await generateScripts(eventName, summaryText, eraLabel);
    console.log(`[Ingest Worker] Generated 4 scripts for ${eventName}, pushing to TTS queue`);
    
    await ttsQueue.add('generate', { eventId, scripts });
    return { status: 'scripts_generated' };

}, { connection, concurrency: 5 });


// --- WORKER 2: ElevenLabs TTS & Mixing ---

const ttsWorker = new Worker('tts', async job => {
    const { eventId, scripts } = job.data;
    console.log(`[TTS Worker] Generating and Mixing audio for event ${eventId}`);
    
    const processedFiles: Record<string, string> = {}; // { perspective: localTmpPath }

    // Sequential loop to respect API rate limits mostly, but can be parallel if paid tier
    for (const [perspective, text] of Object.entries(scripts)) {
         console.log(`  -> Synthesizing voice for ${perspective}`);
         const rawAudioBuffer = await generateAudio(perspective, text as string);
         
         const mixedBuffer = await mixAudioFiles(rawAudioBuffer, null); // Mock ambient passed as null for simplicity locally
         
         const tmpPath = `/tmp/mixed_${eventId}_${perspective}.mp3`;
         await fs.writeFile(tmpPath, mixedBuffer);
         processedFiles[perspective] = tmpPath;
    }

    console.log(`[TTS Worker] Finished processing audio, pushing to Store queue`);
    await storeQueue.add('save', { eventId, processedFiles });
    return { status: 'audio_ready' };

}, { connection, concurrency: 2 });


// --- WORKER 3: Storage & DB ---

const storeWorker = new Worker('store', async job => {
    const { eventId, processedFiles } = job.data;
    console.log(`[Store Worker] Uploading audio to S3 and writing to DB for event ${eventId}`);
    
    for (const [perspective, localPath] of Object.entries(processedFiles)) {
        const s3Key = `events/${eventId}/${perspective}.mp3`;
        
        // Read the local file generated by the TTS worker
        const buffer = await fs.readFile(localPath as string);
        
        // Upload to S3
        await uploadAudio(buffer, s3Key);
        
        // Write to Postgres metadata table
        await saveAudioRecord(eventId, perspective, s3Key, 60);
        
        // Cleanup local temp file
        await fs.unlink(localPath as string).catch(() => {});
    }

    // Mark Event.is_published = true
    await publishEvent(eventId);
    console.log(`[Store Worker] Successfully published event ${eventId}`);

    return { status: 'complete' };

}, { connection, concurrency: 5 });


import express from 'express';

const app = express();
app.use(express.json());

app.post('/generate', async (req, res) => {
    try {
        const { eventId, eventName, summaryText, eraLabel } = req.body;
        
        if (!eventId || !eventName || !summaryText || !eraLabel) {
            return res.status(400).json({ error: "Missing required generation fields" });
        }

        const job = await ingestQueue.add('generate-event', { eventId, eventName, summaryText, eraLabel });
        console.log(`[API] Received generation request for ${eventName}, Job ID: ${job.id}`);
        
        res.json({ message: "Job accepted", jobId: job.id });
    } catch (err) {
        console.error("[API] Generation request error:", err);
        res.status(500).json({ error: "Internal server error" });
    }
});

const PORT = process.env.WORKER_PORT || 3001;
app.listen(PORT, () => {
    console.log(`🤖 EchoTrace Execution Pipeline Running...`);
    console.log(`📡 Worker Trigger API listening on port ${PORT}`);
    console.log(' - Ingest Worker: Waiting for jobs (Generate Scripts)');
    console.log(' - TTS Worker: Waiting for jobs (Voice + Multiplexing)');
    console.log(' - Store Worker: Waiting for jobs (AWS S3 + PostgreSQL)');
});
